# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MardiGras < Formula
  desc "Terminal UI for Beads issue tracking — your issues deserve a parade"
  homepage "https://github.com/quietpublish/mardi-gras"
  version "0.17.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quietpublish/mardi-gras/releases/download/v0.17.0/mardi-gras_0.17.0_darwin_amd64.tar.gz"
      sha256 "cceb71d065226131edfae7d53f82eb4e2cc5f02163bf88bbc362706308e9ec3f"

      define_method(:install) do
        bin.install "mg"
        man1.install "mg.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quietpublish/mardi-gras/releases/download/v0.17.0/mardi-gras_0.17.0_darwin_arm64.tar.gz"
      sha256 "df4d961a270db76a65ee1b6bb4fe3d5ffaa848d5ac516d62356ed1780b953c3c"

      define_method(:install) do
        bin.install "mg"
        man1.install "mg.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quietpublish/mardi-gras/releases/download/v0.17.0/mardi-gras_0.17.0_linux_amd64.tar.gz"
      sha256 "d62e69a809785b06e9d0ff790519785142ea4c9cbc23ed64f98b859fe7335c5d"
      define_method(:install) do
        bin.install "mg"
        man1.install "mg.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quietpublish/mardi-gras/releases/download/v0.17.0/mardi-gras_0.17.0_linux_arm64.tar.gz"
      sha256 "b0c51895183de0597ba142a53725a932c01d3d170b5208e0045cbda2c8c26631"
      define_method(:install) do
        bin.install "mg"
        man1.install "mg.1"
      end
    end
  end
end
