# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MardiGras < Formula
  desc "Terminal UI for Beads issue tracking — your issues deserve a parade"
  homepage "https://github.com/matt-wright86/mardi-gras"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quietpublish/mardi-gras/releases/download/v0.3.0/mardi-gras_0.3.0_darwin_amd64.tar.gz"
      sha256 "a7a3b6fd6b6713abbac2130295d5bc1002368c6a2b11bf91db2cca3cab4178ef"

      define_method(:install) do
        bin.install "mg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quietpublish/mardi-gras/releases/download/v0.3.0/mardi-gras_0.3.0_darwin_arm64.tar.gz"
      sha256 "688aa9f637636de625d9d79c4274582b09ac20324253cf1297e0db8888d33de9"

      define_method(:install) do
        bin.install "mg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quietpublish/mardi-gras/releases/download/v0.3.0/mardi-gras_0.3.0_linux_amd64.tar.gz"
      sha256 "b65c0355bced43d8d7d56f3cae08f699e66886abdb253a5e44dbf97fb03d033d"
      define_method(:install) do
        bin.install "mg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quietpublish/mardi-gras/releases/download/v0.3.0/mardi-gras_0.3.0_linux_arm64.tar.gz"
      sha256 "09faf2c5b5c6e846c0cdf6035ed3efcbd56604b4dd5e7f6539a12a114efb35fb"
      define_method(:install) do
        bin.install "mg"
      end
    end
  end
end
