# This file was generated by GoReleaser. DO NOT EDIT.
cask "mardi-gras" do
  version "0.32.1"

  on_macos do
    on_arm do
      sha256 "161eb05a95d4ad3c4f23ed757adff698e3ea99ea20e1612e820ab3894b78335d"
      url "https://github.com/quietpublish/mardi-gras/releases/download/v#{version}/mardi-gras_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3802ee8d55dd09f91242689e039b0d5ea1d3a8c5b475c082f4d89ecbe5fcf480"
      url "https://github.com/quietpublish/mardi-gras/releases/download/v#{version}/mardi-gras_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "be11b2c7075e09967d118046f8b2fe22741f62ac64cae176f624de835a80f632"
      url "https://github.com/quietpublish/mardi-gras/releases/download/v#{version}/mardi-gras_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b4a214122d7cc30b8aa563858975d2f7da27ce6db981e183c873076b8b5a791c"
      url "https://github.com/quietpublish/mardi-gras/releases/download/v#{version}/mardi-gras_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mardi-gras"
  desc "Terminal UI for Beads issue tracking — your issues deserve a parade"
  homepage "https://github.com/quietpublish/mardi-gras"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mg"
  manpage "mg.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mg"]
    end
  end

  # No zap stanza required
end
