# This file was generated by GoReleaser. DO NOT EDIT.
cask "mardi-gras" do
  version "0.26.0"

  on_macos do
    on_intel do
      sha256 "ef5e7098febaa56ec6f02270edbab96a8e7d917ae38c16d3bbaad922b3abd57e"
      url "https://github.com/quietpublish/mardi-gras/releases/download/v#{version}/mardi-gras_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f864453eeb38bb24722e9869a4245577fa55e281b4809dec54b329dddd41e1e4"
      url "https://github.com/quietpublish/mardi-gras/releases/download/v#{version}/mardi-gras_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d48db0723912cb4df4d802edb69438f02ec6b240f6c8b0b68dddf54dc14e67d5"
      url "https://github.com/quietpublish/mardi-gras/releases/download/v#{version}/mardi-gras_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "18a1d6b6ba007a88ee3e3560a3b4f5d7394ce0bb8e66f56fef0341f3d0198423"
      url "https://github.com/quietpublish/mardi-gras/releases/download/v#{version}/mardi-gras_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mardi-gras"
  desc "Terminal UI for Beads issue tracking — your issues deserve a parade"
  homepage "https://github.com/quietpublish/mardi-gras"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mg"
  manpage "mg.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mg"]
    end
  end

  # No zap stanza required

end
