# This file was generated by GoReleaser. DO NOT EDIT.
cask "mardi-gras" do
  version "0.29.1"

  on_macos do
    on_intel do
      sha256 "afdb6498dfa9dfb26552c27c03d59ab05b96968503bccab3fdfee387b77a2c32"
      url "https://github.com/quietpublish/mardi-gras/releases/download/v#{version}/mardi-gras_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6522b1f6780f858509841dfe130ec3f9812f2cd359620b594b72594373eb5689"
      url "https://github.com/quietpublish/mardi-gras/releases/download/v#{version}/mardi-gras_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cd1c83b26f0438344e2a0e1cc6e4116c278f41ecaaf3d6fe16fc14c5e4e38dc7"
      url "https://github.com/quietpublish/mardi-gras/releases/download/v#{version}/mardi-gras_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aba1add8ed2176ccebd60a673b00b572fb5af91d81415de1d28445543ec63e71"
      url "https://github.com/quietpublish/mardi-gras/releases/download/v#{version}/mardi-gras_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mardi-gras"
  desc "Terminal UI for Beads issue tracking — your issues deserve a parade"
  homepage "https://github.com/quietpublish/mardi-gras"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mg"
  manpage "mg.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mg"]
    end
  end

  # No zap stanza required

end
